In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
covid = pd.read_csv("C:/Users/donaj/jdszr15-ITdepends/covid_data.csv")
covid

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,...,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
0,2,1,1,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,2,1,9999-99-99,97,2,40,97,2,...,2,2,2,2,2,2,2,2,7,97
1048571,1,13,2,2,9999-99-99,2,2,51,97,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,2,1,9999-99-99,97,2,55,97,2,...,2,2,2,2,2,2,2,2,7,97
1048573,2,13,2,1,9999-99-99,97,2,28,97,2,...,2,2,2,2,2,2,2,2,7,97
1048574,2,13,2,1,9999-99-99,97,2,52,97,2,...,2,2,2,2,2,2,2,2,7,97

In [5]:
covid.sample(20)

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,...,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
359109,2,6,2,1,9999-99-99,97,2,57,97,2,...,2,2,2,2,2,2,2,2,3,97
101957,2,4,1,1,9999-99-99,97,1,45,2,2,...,2,2,2,2,2,2,2,2,3,97
780104,2,12,2,1,9999-99-99,97,2,2,97,2,...,2,2,2,2,2,2,2,2,7,97
255276,2,4,2,1,9999-99-99,97,2,40,97,2,...,2,2,2,2,2,2,2,2,7,97
762867,2,12,1,1,9999-99-99,97,2,37,2,2,...,2,2,2,2,2,1,2,2,7,97
61526,2,4,1,1,9999-99-99,97,2,33,2,2,...,2,2,2,2,2,2,2,2,3,97
460930,2,12,1,2,25/06/2020,2,2,27,2,2,...,1,2,2,2,2,2,2,2,7,2
43416,1,4,1,2,20/06/2020,1,2,74,2,1,...,2,2,1,1,2,2,2,2,7,2
157491,1,4,2,2,9999-99-99,2,2,58,97,2,...,2,2,1,2,2,2,2,2,3,2
559529,2,12,2,1,9999-99-99,97,2,56,97,2,...,2,2,2,2,2,2,2,2,3,97
124923,1,4,1,1,9999-99-99,97,2,50,2,2,...,2,2,2,2,2,2,2,2,3,97
364432,1,6,1,1,9999-99-99,97,2,33,2,2,...,2,2,2,2,2,2,2,2,6,97
86262,1,4,2,1,9999-99-99,97,2,68,97,2,...,1,2,1,2,2,1,2,2,3,97
286979,2,4,1,1,9999-99-99,97,2,39,2,2,...,2,2,2,2,2,2,2,2,7,97
135419,2,4,2,1,9999-99-99,97,2,22,97,2,...,2,2,2,2,2,1,2,2,3,97
131888,2,4,1,1,9999-99-99,97,2,26,2,2,...,2,2,2,2,2,2,2,2,3,97
39943,1,4,1,2,13/06/2020,1,1,80,2,1,...,2,2,1,2,2,2,2,2,3,2
657542,2,12,2,1,9999-99-99,97,2,33,97,2,...,2,2,2,2,2,2,2,2,3,97
549503,2,12,2,1,9999-99-99,97,2,57,97,2,...,2,2,2,2,2,2,2,2,3,97
487703,2,12,1,1,9999-99-99,97,2,31,2,2,...,2,2,2,2,2,2,2,2,3,97

In [6]:
covid.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   USMER                 1048575 non-null  int64
 1   MEDICAL_UNIT          1048575 non-null  int64
 2   SEX                   1048575 non-null  int64
 3   PATIENT_TYPE          1048575 non-null  int64
 4   DATE_DIED             1048575 non-null  object
 5   INTUBED               1048575 non-null  int64
 6   PNEUMONIA             1048575 non-null  int64
 7   AGE                   1048575 non-null  int64
 8   PREGNANT              1048575 non-null  int64
 9   DIABETES              1048575 non-null  int64
 10  COPD                  1048575 non-null  int64
 11  ASTHMA                1048575 non-null  int64
 12  INMSUPR               1048575 non-null  int64
 13  HIPERTENSION          1048575 non-null  int64
 14  OTHER_DISEASE         1048575 non-null  int64
 15  CARDIOVASCULAR        1048575 non-null  int64
 16  OBESITY               1048575 non-null  int64
 17  RENAL_CHRONIC         1048575 non-null  int64
 18  TOBACCO               1048575 non-null  int64
 19  CLASIFFICATION_FINAL  1048575 non-null  int64
 20  ICU                   1048575 non-null  int64
dtypes: int64(20), object(1)
memory usage: 168.0+ MB

In [7]:
# sprawdzanie czy są puste komórki ('null')
covid.isnull().sum() # synonim: covid.isna().sum()

USMER                   0
MEDICAL_UNIT            0
SEX                     0
PATIENT_TYPE            0
DATE_DIED               0
INTUBED                 0
PNEUMONIA               0
AGE                     0
PREGNANT                0
DIABETES                0
COPD                    0
ASTHMA                  0
INMSUPR                 0
HIPERTENSION            0
OTHER_DISEASE           0
CARDIOVASCULAR          0
OBESITY                 0
RENAL_CHRONIC           0
TOBACCO                 0
CLASIFFICATION_FINAL    0
ICU                     0
dtype: int64

In [8]:

pd.set_option("display.float_format", lambda x: '%.0f' % x) # zmiana na wyświetlanie danych liczbowych bez "e"

In [9]:

covid.describe()

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,COPD,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
count,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575
mean,2,9,1,1,80,3,42,50,2,2,2,2,2,2,2,2,2,2,5,80
std,0,4,0,0,37,12,17,48,5,5,5,5,5,7,5,5,5,5,2,37
min,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1
25%,1,4,1,1,97,2,30,2,2,2,2,2,2,2,2,2,2,2,3,97
50%,2,12,1,1,97,2,40,97,2,2,2,2,2,2,2,2,2,2,6,97
75%,2,12,2,1,97,2,53,97,2,2,2,2,2,2,2,2,2,2,7,97
max,2,13,2,2,99,99,121,98,98,98,98,98,98,98,98,98,98,98,7,99

In [10]:
# sprawdzanie czy są zduplikowane wiersze
covid.duplicated().sum()

812049

In [11]:
# usunięcie zduplikowanych wierszy
covid.drop_duplicates(inplace=True)

In [12]:
covid.duplicated().sum()

0

In [13]:
# usunięcie kolumn, które nic nie mówią
covid.drop(columns=['MEDICAL_UNIT','USMER'], inplace =True)
covid

,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,COPD,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
0,1,1,03/05/2020,97,1,65,2,2,2,2,2,1,2,2,2,2,2,3,97
1,2,1,03/06/2020,97,1,72,97,2,2,2,2,1,2,2,1,1,2,5,97
2,2,2,09/06/2020,1,2,55,97,1,2,2,2,2,2,2,2,2,2,3,2
3,1,1,12/06/2020,97,2,53,2,2,2,2,2,2,2,2,2,2,2,7,97
4,2,1,21/06/2020,97,2,68,97,1,2,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048568,2,1,9999-99-99,97,2,47,97,1,2,2,2,2,2,2,2,2,2,7,97
1048569,1,2,9999-99-99,2,2,56,2,1,2,2,2,2,2,2,2,2,2,7,2
1048571,2,2,9999-99-99,2,2,51,97,2,2,2,2,1,2,2,2,2,2,7,2
1048572,2,1,9999-99-99,97,2,55,97,2,2,2,2,2,2,2,2,2,2,7,97
1048574,2,1,9999-99-99,97,2,52,97,2,2,2,2,2,2,2,2,2,2,7,97

In [14]:
covid.rename(columns=
             {'PATIENT_TYPE':'HOSPITALIZED',
              'DATE_DIED':'DEAD',
              'INMSUPR': 'IMMUNOSUPPRESSED',
              'CLASIFFICATION_FINAL': 'COVID_TEST_RESULT',
              'TOBACCO': "SMOKER",
              'CARDIOVASCULAR': 'CARDIOVASCULAR_DISEASE',
              'RENAL_CHRONIC': 'CHRONIC_KIDNEY_DISEASE',
              'ICU': 'ADMITTED_TO_ICU'}, inplace=True)
covid

,SEX,HOSPITALIZED,DEAD,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,COPD,ASTHMA,IMMUNOSUPPRESSED,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR_DISEASE,OBESITY,CHRONIC_KIDNEY_DISEASE,SMOKER,COVID_TEST_RESULT,ADMITTED_TO_ICU
0,1,1,03/05/2020,97,1,65,2,2,2,2,2,1,2,2,2,2,2,3,97
1,2,1,03/06/2020,97,1,72,97,2,2,2,2,1,2,2,1,1,2,5,97
2,2,2,09/06/2020,1,2,55,97,1,2,2,2,2,2,2,2,2,2,3,2
3,1,1,12/06/2020,97,2,53,2,2,2,2,2,2,2,2,2,2,2,7,97
4,2,1,21/06/2020,97,2,68,97,1,2,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048568,2,1,9999-99-99,97,2,47,97,1,2,2,2,2,2,2,2,2,2,7,97
1048569,1,2,9999-99-99,2,2,56,2,1,2,2,2,2,2,2,2,2,2,7,2
1048571,2,2,9999-99-99,2,2,51,97,2,2,2,2,1,2,2,2,2,2,7,2
1048572,2,1,9999-99-99,97,2,55,97,2,2,2,2,2,2,2,2,2,2,7,97
1048574,2,1,9999-99-99,97,2,52,97,2,2,2,2,2,2,2,2,2,2,7,97

In [15]:
covid = covid.loc[:,
                  ['COVID_TEST_RESULT', 
                   'HOSPITALIZED',
                   'INTUBED',
                   'ADMITTED_TO_ICU',
                   'DEAD',
                   'AGE',
                   'SEX',
                   'PREGNANT',
                   'SMOKER',
                   'PNEUMONIA',
                   'COPD',
                   'ASTHMA',
                   'IMMUNOSUPPRESSED',
                   'CARDIOVASCULAR_DISEASE',
                   'HIPERTENSION',
                   'CHRONIC_KIDNEY_DISEASE',
                   'DIABETES',
                   'OBESITY',
                   'OTHER_DISEASE']]
covid

,COVID_TEST_RESULT,HOSPITALIZED,INTUBED,ADMITTED_TO_ICU,DEAD,AGE,SEX,PREGNANT,SMOKER,PNEUMONIA,COPD,ASTHMA,IMMUNOSUPPRESSED,CARDIOVASCULAR_DISEASE,HIPERTENSION,CHRONIC_KIDNEY_DISEASE,DIABETES,OBESITY,OTHER_DISEASE
0,3,1,97,97,03/05/2020,65,1,2,2,1,2,2,2,2,1,2,2,2,2
1,5,1,97,97,03/06/2020,72,2,97,2,1,2,2,2,2,1,1,2,1,2
2,3,2,1,2,09/06/2020,55,2,97,2,2,2,2,2,2,2,2,1,2,2
3,7,1,97,97,12/06/2020,53,1,2,2,2,2,2,2,2,2,2,2,2,2
4,3,1,97,97,21/06/2020,68,2,97,2,2,2,2,2,2,1,2,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048568,7,1,97,97,9999-99-99,47,2,97,2,2,2,2,2,2,2,2,1,2,2
1048569,7,2,2,2,9999-99-99,56,1,2,2,2,2,2,2,2,2,2,1,2,2
1048571,7,2,2,2,9999-99-99,51,2,97,2,2,2,2,2,2,1,2,2,2,2
1048572,7,1,97,97,9999-99-99,55,2,97,2,2,2,2,2,2,2,2,2,2,2
1048574,7,1,97,97,9999-99-99,52,2,97,2,2,2,2,2,2,2,2,2,2,2

In [16]:
# zamiana wartości w kolumnie "DEAD" na odpowiedź czy zmarł: 1, czyli "True" zamiast daty śmierci, oraz 0 czyli "False" zamiast 9999-99-99 
covid['DEAD'] = covid['DEAD'].replace({'9999-99-99': 0})
covid['DEAD'] = covid['DEAD'].apply(lambda x: 1 if x != 0 else 0)
covid

,COVID_TEST_RESULT,HOSPITALIZED,INTUBED,ADMITTED_TO_ICU,DEAD,AGE,SEX,PREGNANT,SMOKER,PNEUMONIA,COPD,ASTHMA,IMMUNOSUPPRESSED,CARDIOVASCULAR_DISEASE,HIPERTENSION,CHRONIC_KIDNEY_DISEASE,DIABETES,OBESITY,OTHER_DISEASE
0,3,1,97,97,1,65,1,2,2,1,2,2,2,2,1,2,2,2,2
1,5,1,97,97,1,72,2,97,2,1,2,2,2,2,1,1,2,1,2
2,3,2,1,2,1,55,2,97,2,2,2,2,2,2,2,2,1,2,2
3,7,1,97,97,1,53,1,2,2,2,2,2,2,2,2,2,2,2,2
4,3,1,97,97,1,68,2,97,2,2,2,2,2,2,1,2,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048568,7,1,97,97,0,47,2,97,2,2,2,2,2,2,2,2,1,2,2
1048569,7,2,2,2,0,56,1,2,2,2,2,2,2,2,2,2,1,2,2
1048571,7,2,2,2,0,51,2,97,2,2,2,2,2,2,1,2,2,2,2
1048572,7,1,97,97,0,55,2,97,2,2,2,2,2,2,2,2,2,2,2
1048574,7,1,97,97,0,52,2,97,2,2,2,2,2,2,2,2,2,2,2

In [17]:
covid['SEX'] = covid['SEX'].replace({1: 'female', 2: 'male'})
covid

,COVID_TEST_RESULT,HOSPITALIZED,INTUBED,ADMITTED_TO_ICU,DEAD,AGE,SEX,PREGNANT,SMOKER,PNEUMONIA,COPD,ASTHMA,IMMUNOSUPPRESSED,CARDIOVASCULAR_DISEASE,HIPERTENSION,CHRONIC_KIDNEY_DISEASE,DIABETES,OBESITY,OTHER_DISEASE
0,3,1,97,97,1,65,female,2,2,1,2,2,2,2,1,2,2,2,2
1,5,1,97,97,1,72,male,97,2,1,2,2,2,2,1,1,2,1,2
2,3,2,1,2,1,55,male,97,2,2,2,2,2,2,2,2,1,2,2
3,7,1,97,97,1,53,female,2,2,2,2,2,2,2,2,2,2,2,2
4,3,1,97,97,1,68,male,97,2,2,2,2,2,2,1,2,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048568,7,1,97,97,0,47,male,97,2,2,2,2,2,2,2,2,1,2,2
1048569,7,2,2,2,0,56,female,2,2,2,2,2,2,2,2,2,1,2,2
1048571,7,2,2,2,0,51,male,97,2,2,2,2,2,2,1,2,2,2,2
1048572,7,1,97,97,0,55,male,97,2,2,2,2,2,2,2,2,2,2,2
1048574,7,1,97,97,0,52,male,97,2,2,2,2,2,2,2,2,2,2,2

In [18]:
# sprawdzenie ile jest unikatowych wartości (i jakie to są wartości) dla każdej kolumny
for column_title in covid.columns:
    print(column_title, covid[column_title].unique(), covid[column_title].nunique())

COVID_TEST_RESULT [3 5 7 6 1 2 4] 7
HOSPITALIZED [1 2] 2
INTUBED [97  1  2 99] 4
ADMITTED_TO_ICU [97  2  1 99] 4
DEAD [1 0] 2
AGE [ 65  72  55  53  68  40  64  37  25  38  24  30  48  23  80  61  54  59
  45  26  32  49  39  27  57  20  56  47  50  46  43  28  33  16  62  58
  36  44  66  52  51  35  19  90  34  22  29  14  31  42  15   1   0  17
  41   2  10  12  13   4   7   6   8  60   5  63  75  81  67  18  70  88
  85  92  73  74  78  76  82  77  86  71  95  87  83  84  79  69  89   3
  97  93 100  91  21 103  11   9  94  96 101 107 102  98  99 109 119 116
 105 104 111 114 120 106 108 110 118 117 121 115 113] 121
SEX ['female' 'male'] 2
PREGNANT [ 2 97 98  1] 4
SMOKER [ 2  1 98] 3
PNEUMONIA [ 1  2 99] 3
COPD [ 2  1 98] 3
ASTHMA [ 2  1 98] 3
IMMUNOSUPPRESSED [ 2  1 98] 3
CARDIOVASCULAR_DISEASE [ 2  1 98] 3
HIPERTENSION [ 1  2 98] 3
CHRONIC_KIDNEY_DISEASE [ 2  1 98] 3
DIABETES [ 2  1 98] 3
OBESITY [ 2  1 98] 3
OTHER_DISEASE [ 2  1 98] 3

In [19]:
# zamiana 2 na 0 ('False"), 97, 98 i 99 na 'NaN' (Not a Number). Wartości 'NaN' są automatycznie wykluczane przy tworzeniu wykresów.
covid[['INTUBED','ADMITTED_TO_ICU','PREGNANT','SMOKER','PNEUMONIA','COPD','ASTHMA','IMMUNOSUPPRESSED',
       'CARDIOVASCULAR_DISEASE','HIPERTENSION','CHRONIC_KIDNEY_DISEASE', 'DIABETES','OBESITY','OTHER_DISEASE']] = covid[[
           'INTUBED','ADMITTED_TO_ICU','PREGNANT','SMOKER','PNEUMONIA','COPD','ASTHMA','IMMUNOSUPPRESSED',
           'CARDIOVASCULAR_DISEASE','HIPERTENSION', 'CHRONIC_KIDNEY_DISEASE','DIABETES','OBESITY','OTHER_DISEASE']].replace({2: 0, 97: 'NaN', 98: 'NaN', 99: 'NaN'})

In [20]:
# tu znaczenie 1 i 2 jest odwrotne niż w reszcie kolumn , dlatego zamieniam te wartości osobno
covid['HOSPITALIZED'] = covid['HOSPITALIZED'].replace({1: 0, 2: 1})
covid

,COVID_TEST_RESULT,HOSPITALIZED,INTUBED,ADMITTED_TO_ICU,DEAD,AGE,SEX,PREGNANT,SMOKER,PNEUMONIA,COPD,ASTHMA,IMMUNOSUPPRESSED,CARDIOVASCULAR_DISEASE,HIPERTENSION,CHRONIC_KIDNEY_DISEASE,DIABETES,OBESITY,OTHER_DISEASE
0,3,0,NaN,NaN,1,65,female,0,0,1,0,0,0,0,1,0,0,0,0
1,5,0,NaN,NaN,1,72,male,NaN,0,1,0,0,0,0,1,1,0,1,0
2,3,1,1,0,1,55,male,NaN,0,0,0,0,0,0,0,0,1,0,0
3,7,0,NaN,NaN,1,53,female,0,0,0,0,0,0,0,0,0,0,0,0
4,3,0,NaN,NaN,1,68,male,NaN,0,0,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048568,7,0,NaN,NaN,0,47,male,NaN,0,0,0,0,0,0,0,0,1,0,0
1048569,7,1,0,0,0,56,female,0,0,0,0,0,0,0,0,0,1,0,0
1048571,7,1,0,0,0,51,male,NaN,0,0,0,0,0,0,1,0,0,0,0
1048572,7,0,NaN,NaN,0,55,male,NaN,0,0,0,0,0,0,0,0,0,0,0
1048574,7,0,NaN,NaN,0,52,male,NaN,0,0,0,0,0,0,0,0,0,0,0

In [21]:
covid['COVID_TEST_RESULT'] = covid['COVID_TEST_RESULT'].apply(lambda x: 1 if x in [1,2,3] else 0)
covid.sample(30)

,COVID_TEST_RESULT,HOSPITALIZED,INTUBED,ADMITTED_TO_ICU,DEAD,AGE,SEX,PREGNANT,SMOKER,PNEUMONIA,COPD,ASTHMA,IMMUNOSUPPRESSED,CARDIOVASCULAR_DISEASE,HIPERTENSION,CHRONIC_KIDNEY_DISEASE,DIABETES,OBESITY,OTHER_DISEASE
563964,1,1,0,0,0,62,female,0,0,0,0,0,0,0,0,0,1,0,0
716191,0,0,NaN,NaN,0,58,male,NaN,0,0,0,0,0,1,0,0,0,1,0
1007934,0,1,0,0,0,27,male,NaN,0,0,0,0,0,0,0,1,0,0,0
227397,0,1,0,1,0,85,male,NaN,0,1,0,0,0,0,1,0,1,0,0
453115,1,1,1,0,1,63,male,NaN,0,1,0,0,0,0,0,0,1,0,0
537495,1,0,NaN,NaN,0,64,female,0,0,0,0,1,1,0,1,0,1,0,0
677226,0,0,NaN,NaN,0,68,male,NaN,0,NaN,0,0,0,0,0,0,0,0,0
352943,1,1,0,1,0,60,female,0,0,0,0,0,0,0,1,0,0,0,0
206814,0,1,0,0,0,74,female,0,0,1,0,0,0,0,1,0,1,0,1
249081,0,1,0,0,0,85,female,0,0,1,0,0,0,1,1,1,0,0,0
446024,1,1,1,0,1,42,female,0,0,1,0,0,0,0,0,0,1,1,0
385803,1,1,0,0,0,47,male,NaN,0,1,0,0,0,0,0,0,1,1,0
395596,1,0,NaN,NaN,0,40,male,NaN,0,0,0,0,0,0,0,0,0,0,0
445913,0,1,0,1,1,76,male,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
333914,0,1,0,0,1,83,male,NaN,0,1,0,0,0,0,1,0,0,0,1
50869,1,1,1,0,1,68,female,0,0,1,0,0,0,0,1,0,1,0,0
342197,0,1,1,0,1,48,male,NaN,1,1,0,0,1,1,1,1,0,1,0
665170,0,1,0,0,0,59,male,NaN,0,0,0,0,0,0,0,0,0,0,0
26252,1,1,1,0,1,53,male,NaN,0,1,0,0,0,0,1,0,0,0,0
681738,0,0,NaN,NaN,0,32,female,0,0,0,0,0,0,0,1,0,0,1,0
459745,1,1,NaN,NaN,1,67,male,NaN,0,1,0,0,0,0,1,0,0,0,0
464693,1,1,1,1,1,64,male,NaN,0,1,0,0,0,0,0,0,0,0,0
397468,1,0,NaN,NaN,0,29,female,0,0,0,0,0,0,0,0,0,0,1,0
437825,0,1,0,1,0,47,female,0,0,1,0,1,0,0,0,0,0,1,0
862377,0,0,NaN,NaN,0,44,female,0,0,0,0,0,0,0,0,0,0,0,1
727703,0,1,0,0,0,49,male,NaN,1,1,0,0,0,0,0,0,0,0,0
446563,0,1,0,0,1,59,male,NaN,0,0,0,0,0,0,1,0,1,0,0
662048,0,0,NaN,NaN,0,24,male,NaN,0,0,0,0,0,0,0,0,0,0,0
148365,1,0,NaN,NaN,0,36,female,0,1,0,0,0,0,0,1,0,1,0,0
468003,1,1,0,0,1,70,female,0,0,1,1,1,0,1,0,0,1,0,0

In [22]:
for column_title in covid.columns:
    print(column_title, covid[column_title].unique(), covid[column_title].nunique())

COVID_TEST_RESULT [1 0] 2
HOSPITALIZED [0 1] 2
INTUBED ['NaN' 1 0] 3
ADMITTED_TO_ICU ['NaN' 0 1] 3
DEAD [1 0] 2
AGE [ 65  72  55  53  68  40  64  37  25  38  24  30  48  23  80  61  54  59
  45  26  32  49  39  27  57  20  56  47  50  46  43  28  33  16  62  58
  36  44  66  52  51  35  19  90  34  22  29  14  31  42  15   1   0  17
  41   2  10  12  13   4   7   6   8  60   5  63  75  81  67  18  70  88
  85  92  73  74  78  76  82  77  86  71  95  87  83  84  79  69  89   3
  97  93 100  91  21 103  11   9  94  96 101 107 102  98  99 109 119 116
 105 104 111 114 120 106 108 110 118 117 121 115 113] 121
SEX ['female' 'male'] 2
PREGNANT [0 'NaN' 1] 3
SMOKER [0 1 'NaN'] 3
PNEUMONIA [1 0 'NaN'] 3
COPD [0 1 'NaN'] 3
ASTHMA [0 1 'NaN'] 3
IMMUNOSUPPRESSED [0 1 'NaN'] 3
CARDIOVASCULAR_DISEASE [0 1 'NaN'] 3
HIPERTENSION [1 0 'NaN'] 3
CHRONIC_KIDNEY_DISEASE [0 1 'NaN'] 3
DIABETES [0 1 'NaN'] 3
OBESITY [0 1 'NaN'] 3
OTHER_DISEASE [0 1 'NaN'] 3

In [23]:
covid.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Index: 236526 entries, 0 to 1048574
Data columns (total 19 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   COVID_TEST_RESULT       236526 non-null  int64
 1   HOSPITALIZED            236526 non-null  int64
 2   INTUBED                 236526 non-null  object
 3   ADMITTED_TO_ICU         236526 non-null  object
 4   DEAD                    236526 non-null  int64
 5   AGE                     236526 non-null  int64
 6   SEX                     236526 non-null  object
 7   PREGNANT                236526 non-null  object
 8   SMOKER                  236526 non-null  object
 9   PNEUMONIA               236526 non-null  object
 10  COPD                    236526 non-null  object
 11  ASTHMA                  236526 non-null  object
 12  IMMUNOSUPPRESSED        236526 non-null  object
 13  CARDIOVASCULAR_DISEASE  236526 non-null  object
 14  HIPERTENSION            236526 non-null  object
 15  CHRONIC_KIDNEY_DISEASE  236526 non-null  object
 16  DIABETES                236526 non-null  object
 17  OBESITY                 236526 non-null  object
 18  OTHER_DISEASE           236526 non-null  object
dtypes: int64(4), object(15)
memory usage: 36.1+ MB

In [24]:
covid.to_csv('covid_v1', index=False)